[factchecker]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.mt-2.text-xl.font-medium.text-gray-900"
linkSelector = "div.mt-2.text-xl.font-medium.text-gray-900 a"
contentSelector = "div.mt-2.text-sm.text-gray-600.line-clamp-2"
waitUntil = "networkidle"

[subjects]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/turbo-frame/li"
titleSelector = "//div[1]/div[1]/div[2]/a/text()"
linkSelector = "//div[1]/div[1]/div[2]/a/@href"
contentSelector = "//div[1]/div[1]/div[3]/a/text()"
imageSelector = "//div[1]/div[2]/div/div[1]/img[@class='w-full hidden md:inline']/@src"
waitUntil = "networkidle"
onFail = "stale"
