[factchecker]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.mt-2.text-xl.font-medium.text-gray-900"
linkSelector = "div.mt-2.text-xl.font-medium.text-gray-900 a"
contentSelector = "div.mt-2.text-sm.text-gray-600.line-clamp-2"
waitUntil = "networkidle"
onFail = "stale"

[subjects]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/turbo-frame/li"
titleSelector = "//div[1]/div[1]/div[2]/a"
linkSelector = "//div[1]/div[1]/div[2]/a"
contentSelector = "//div[1]/div[1]/div[3]/a"
imageSelector = "//div[1]/div[2]/div/div[1]/img[@class='w-full hidden md:inline']"
waitUntil = "networkidle"
onFail = "stale"

[press]
title = "팩트체크넷 ─ 언론사"
url = "https://factchecker.or.kr/fc_archives/press"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.h5.text-base.font-medium.md:text-xl.uppercase.md:mt-2 > a"
linkSelector = "div.h5.text-base.font-medium.md:text-xl.uppercase.md:mt-2 > a"
contentSelector = "div.hidden.md:line-clamp-2.text-sm.text-gray-600.mt-2"
imageSelector = "div.flex-none.min-h-18.w-22.md\:w-44.border-solid.border.bg-gray-100.md:-mt-4 > a > img"
waitUntil = "networkidle"
onFail = "stale"
