[factchecker]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.mt-2.text-xl.font-medium.text-gray-900"
linkSelector = "div.mt-2.text-xl.font-medium.text-gray-900 a"
contentSelector = "div.mt-2.text-sm.text-gray-600.line-clamp-2"
waitUntil = "networkidle"
onFail = "stale"

[subjects]
title = "팩트체크넷 ─ 검증센터 ─ 팩트 검증"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/turbo-frame/li"
titleSelector = "//div[1]/div[1]/div[2]/a"
linkSelector = "//div[1]/div[1]/div[2]/a"
contentSelector = "//div[1]/div[1]/div[3]/a"
imageSelector = "//div[1]/div[2]/div/div[1]/img[@class='w-full hidden md:inline']"
waitUntil = "networkidle"
onFail = "stale"

[suggests]
title = "팩트체크넷 ─ 검증센터 ─ 검증 제안"
url = "https://factchecker.or.kr/fc_suggests"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/turbo-frame/li"
titleSelector = "//div/div/div[1]/a/div[1]/span[2]"
linkSelector = "//div/div/div[1]/a"
contentSelector = "//div/div/div[1]/a/div[2]"
waitUntil = "networkidle"
onFail = "stale"

[press]
title = "팩트체크넷 ─ 팩트체크 ─ 언론사"
url = "https://factchecker.or.kr/fc_archives/press"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/li"
titleSelector = "//div[2]/div[1]/div[1]/div[1]/a"
linkSelector = "//div[2]/div[1]/div[1]/div[1]/a"
contentSelector = "//div[2]/div[1]/div[1]/div[2]"
imageSelector = "//div[2]/div[2]/a/img"
dateSelector = "//div[2]/div[1]/div[1]/div[3]/div"
dateFormat = " yyyy.MM.dd "
waitUntil = "networkidle"
onFail = "stale"

[gov]
title = "팩트체크넷 ─ 팩트체크 ─ 정부기관"
url = "https://factchecker.or.kr/fc_archives/gov"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/li"
titleSelector = "//div[2]/div[1]/div[1]/div[1]/a"
linkSelector = "//div[2]/div[1]/div[1]/div[1]/a"
contentSelector = "//div[2]/div[1]/div[1]/div[2]"
imageSelector = "//div[2]/div[2]/a/img"
dateSelector = "//div[2]/div[1]/div[1]/div[3]/div"
dateFormat = " yyyy.MM.dd "
waitUntil = "networkidle"
onFail = "stale"

[publications]
title = "팩트체크넷 ─ 팩트체크 ─ 언론사"
url = "https://factchecker.or.kr/fc_publications"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/li"
titleSelector = "//div/div/div[2]/a"
linkSelector = "//div/div/div[2]/a"
contentSelector = "//div/div/div[3]/a"
dateSelector = "//div/div/div[4]/div/div"
dateFormat = " yyyy.MM.dd "
waitUntil = "networkidle"
onFail = "stale"

[trends]
title = "팩트체크넷 ─ 자료실 ─ 주요동향"
url = "https://factchecker.or.kr/trends"
entrySelector = "//html/body/div[1]/main/div[2]/div/div[3]/div"
titleSelector = "//a/div[1]"
linkSelector = "//a"
contentSelector = "//a/div[2]"
dateSelector = "//div/div/span/span"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"
