[factchecker]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.mt-2.text-xl.font-medium.text-gray-900"
linkSelector = "div.mt-2.text-xl.font-medium.text-gray-900 a"
contentSelector = "div.mt-2.text-sm.text-gray-600.line-clamp-2"
waitUntil = "networkidle"
onFail = "stale"

[subjects]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/turbo-frame/li"
titleSelector = "//div[1]/div[1]/div[2]/a"
linkSelector = "//div[1]/div[1]/div[2]/a"
contentSelector = "//div[1]/div[1]/div[3]/a"
imageSelector = "//div[1]/div[2]/div/div[1]/img[@class='w-full hidden md:inline']"
waitUntil = "networkidle"
onFail = "stale"

[press]
title = "팩트체크넷 ─ 언론사"
url = "https://factchecker.or.kr/fc_archives/press"
entrySelector = "//html/body/div[1]/main/div[2]/div[1]/ul/li"
titleSelector = "//div[2]/div[1]/div[1]/div[1]/a"
linkSelector = "//div[2]/div[1]/div[1]/div[1]/a"
contentSelector = "//div[2]/div[1]/div[1]/div[2]"
imageSelector = "div[2]/div[2]/a/img"
dateSelector = "//div[2]/div[1]/div[1]/div[3]/div"
dateFormat = " yyyy.MM.dd "
waitUntil = "networkidle
onFail = "stale"
