[factchecker]
title = "팩트체크넷"
url = "https://factchecker.or.kr/fc_subjects"
entrySelector = "ul li.py-4.h-max.border-b.border-gray-200"
titleSelector = "div.mt-2.text-xl.font-medium.text-gray-900"
linkSelector = "div.mt-2.text-xl.font-medium.text-gray-900 a"
contentSelector = "div.mt-2.text-sm.text-gray-600.line-clamp-2"
waitUntil = "networkidle"
